version: "3"
services:
  database:
    image: postgres:11.7-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - ./volumes/postgresql:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      interval: 10s
      retries: 10
      timeout: 2s
    networks:
      - movies-crud

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./server
        target: /app
      - /app/node_modules
      - /app/prisma
    restart: unless-stopped
    ports:
      - "8080:8080"
    stdin_open: true
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/postgres?schem=public
      - ACCESS_KEY_JWT_SECRET=access_key_secret
      - REFRESH_KEY_JWT_SECRET=refresh_key_secret
    depends_on:
      - database
    networks:
      - movies-crud

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./web
        target: /app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_BASE_PATH=/.taskphin/movies-crud/web
      - NEXT_PUBLIC_SERVER_URL=http://127.0.0.1:4455/.taskphin/movies-crud/server
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - movies-crud

  oathkeeper:
    image: oryd/oathkeeper:latest-alpine
    ports:
      - "4455:4455"
      - "4456:4456"
    environment:
      - LOG_LEVEL=debug
    volumes:
      - type: bind
        source: ./oathkeeper
        target: /etc/config/oathkeeper
    command: serve proxy -c "/etc/config/oathkeeper/.oathkeeper.yml"
    restart: on-failure
    networks:
      - movies-crud

networks:
  movies-crud:
