log:
  level: debug
  format: json
  leak_sensitive_values: true

serve:
  proxy:
    cors:
      enabled: true
      allowed_origins:
        - "*"
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
      exposed_headers:
        - Content-Type
      allow_credentials: true
      debug: true

errors:
  fallback:
    - json

  handlers:
    redirect:
      enabled: true
      config:
        to: http://127.0.0.1:4455/.taskphin/movies-crud/web/auth/login
        when:
          - error:
              - unauthorized
              - forbidden
            request:
              header:
                accept:
                  - text/html
    json:
      enabled: true
      config:
        verbose: true

access_rules:
  repositories:
    - file:///etc/config/oathkeeper/access-rules/server.json
    - file:///etc/config/oathkeeper/access-rules/web.json

authorizers:
  allow:
    enabled: true

authenticators:
  anonymous:
    enabled: true
    config:
      subject: guest

  cookie_session:
    enabled: true
    config:
      force_method: "GET"
      check_session_url: http://server:8080/api/sessions/whoami
      extra_from: "@this"
      preserve_path: true
      only:
        - movies-crud-session-cookie
        - movies-crud-refresh-cookie

mutators:
  header:
    enabled: true
    config:
      headers:
        X-User: "{{ print .Subject }}"
        X-Access-Token: "{{ print .Extra.new_access_token }}"
  noop:
    enabled: true
