ARG NODE_VERSION=19-alpine3.16
FROM node:${NODE_VERSION} AS node
FROM node AS builder

# ENV PORT 7770

# Create app directory
RUN mkdir -p /app 
WORKDIR /app

# Copying source files
# Copying source files
COPY . /app

# Installing dependencies
RUN npm install --legacy-peer-deps

# Building app
# RUN npm run build
EXPOSE 3000 

# Running the app
CMD "npm" "run" "dev"































